// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vsebkutzyfdcvrjqyhek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzZWJrdXR6eWZkY3ZyanF5aGVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MDQxMDQsImV4cCI6MjA2MTA4MDEwNH0.SlimVTD4krfuntVAav1hkuv1q6K-rECGeb0xatNtrzo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);